### ISSUE TITLE
Using chef in a pool with > 1 clouds overwrites main/recipes/default.rb in /tmp/poolparty

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#14]
This is a huge break. No multiple clouds for you! 

What _should_ happen is that the name of the file given to #recipe in the chef block shouldn't be changed to default.rb. Then, in dna.json reference "main::<cloudname>" instead of just "main"

PP + Chef is effectively unusable with 1.2 for pools with more than one cloud.

**Comment by contentfree** [comment]
Only way for me to successfully launch an instance from the first cloud (since the second one's recipe call overwrites the first's) is to comment out the latter cloud.

**Comment by contentfree** [comment]
Also potentially related: The clouds seem to be provisioned in reverse order as the appear in clouds.rb. I have a :db cloud, then a :web cloud but when I do `cloud start`, the web cloud is provisioned first and then the db cloud. It should provision in the order given in clouds.rb. (Also, the db cloud is given the recipe file for the web cloud instead of the correct recipe file)

**Comment by auser** [comment]
This has been updated with 1.2.3
