### ISSUE TITLE
During cloud-start, consistently hanging at a certain point

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#15]
Right after rubygems is installed I get this:

http://gems.github.com added to sources
^C/opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:200:in `select': Interrupt
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:200:in`process'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:160:in `loop'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:160:in`loop_forever'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:160:in `loop'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/channel.rb:269:in`wait'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh/connection/session.rb:354:in `exec!'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/../net/remoter/connections.rb:74:in`netssh'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/../net/remoter/connections.rb:73:in `each'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/../net/remoter/connections.rb:73:in`netssh'
        from /opt/local/lib/ruby/gems/1.8/gems/net-ssh-2.0.11/lib/net/ssh.rb:186:in `start'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/../net/remoter/connections.rb:72:in`netssh'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/../net/remoter/connections.rb:58:in `execute!'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/../provision/boot_strapper.rb:67:in`initialize'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/cloud-start:17:in `new'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/cloud-start:17
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/net/remoter_base.rb:116:in`call'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/net/remoter_base.rb:116:in `launch_instance!'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/net/remoter_base.rb:109:in`times'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/net/remoter_base.rb:109:in `launch_instance!'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/cloud.rb:57:in`send'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/../lib/poolparty/poolparty/cloud.rb:57:in `method_missing'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/cloud-start:15
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/cloud-start:9:in`each'
        from /opt/local/lib/ruby/gems/1.8/gems/poolparty-1.2.2/bin/cloud-start:9
        from /opt/local/bin/cloud-start:19:in `load'
        from /opt/local/bin/cloud-start:19

Don't know what it's doing at that point or what it's waiting for. Has happened every time I've run cloud-start tonight. I think have to run cloud-provision to make it through

**Comment by auser** [comment]
Is this with ec2?

**Comment by contentfree** [comment]
Yes, but I didn't see it today. So maybe something else was in a weird state (or github was unavailable)?
