### ISSUE TITLE
There's no way to discern which instance belongs to which cloud

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#16]
This makes using Poolparty to manage multiple pools, say a web pool and a DB pool, impossible. At least on EC2. 

I have two clouds. cloud :web and cloud :db. I've launched an instance for cloud :db, but when I do cloud-list -n web, the DB cloud's instance is shown. Looking at the code for get_instances_description, there's nothing to allow deciphering between clouds.

**Comment by contentfree** [comment]
Is there some way to use tags that could aid this?

**Comment by auser** [comment]
I'm not sure what you mean by tags? How would you use it? Perhaps a code snippet would help

**Comment by auser** [comment]
Open a feature request. I'm going to close this as clouds are differentiated by keypairs on ec2.

**Comment by contentfree** [comment]
If it's really going to be one-keypair-per-cloud then this needs to be made extremely clear in the topmost documentation and examples. This will trip up a lot of people otherwise.
