### ISSUE TITLE
/etc/chef/solo.rb content wrong

### ISSUE THREAD

**Issue by pingali** [auser/poolparty#4]
$ cloud-configure --debug --verbose 
...throws the error...

```
 75.101.252.131 stderr => /usr/lib/ruby/gems/1.8/gems/chef-0.5.6/lib   /chef/cookbook_loader.rb:104:in `[]'75.101.252.131 stderr => : 75.101.252.131 stderr    => Cannot find a cookbook named poolparty75.101.252.131 stderr =>  (75.101.252.131 stderr => ArgumentError75.101.252.131 stderr => )
```

Upon investigation, found that /etc/chef/solo.rb is wrong. Its content is

```
#
# Chef Solo Config File
#
log_level          :info
log_location       STDOUT
file_cache_path    "/tmp/chef-solo"
cookbook_path      "/tmp/chef-solo/cookbooks"
Chef::Log::Formatter.show_time = false
```

instead of 

```
 cookbook_path     "/etc/chef/cookbooks"
 node_path         "/etc/chef/nodes"
 log_level         :info
 file_store_path  "/etc/chef"
 file_cache_path  "/etc/chef"
```

from lib/poolparty/plugins/chef.rb

The /tmp/poolparty/dr_configure is wrong too.

**Comment by auser** [comment]
Whoa... That's interesting, I didn't think it was dynamic. I'll check the solo.rb creation today

**Comment by auser** [comment]
Is this still erroring out?

**Comment by pingali** [comment]
I am still finding the same error. As a work around, I simply changed my desktop's /etc/chef/solo.rb and also made /tmp/chef-repo point to /etc/chef

**Comment by auser** [comment]
Have been unable to reproduce this error.
