### ISSUE TITLE
Machine reservations must be requested together

### ISSUE THREAD

**Issue by tralfamadude** [auser/poolparty#48]
In EC2, a batch of instances can be requested together, but hosts are instantiated one at a time.  This slows down the provisioning process and reduces the likelihood that machines are co-located.

Note that ec2-describe-instances will show batches as a single RESERVATION which helps keep things organized.

**Comment by tralfamadude** [comment]
An example of the speed difference between reserve-all-at-once verses one-at-a-time:

The Hadoop ec2 bash scripts can bring up a 24 node cluster in about 20 minutes.

Poolparty (in Sept. 2009) required about 65 minutes to start up a 24 node cluster (tested with a static image needing no installations).

**Comment by auser** [comment]
This is implemented now to request the minimum number of instances at once.
