### ISSUE TITLE
Using an alternative port for ssh should be supported

### ISSUE THREAD

**Issue by tralfamadude** [auser/poolparty#49]
If a non-standard port for sshd listening (or other ssh, scp options) on spawned nodes is used, the following construction, if supplied at the beginning of a clouds.rb file, is supposed to override the default port (or other ssh or scp -o settings):

module  CloudProviders
  module Connections
    def ssh_options(opts={})
      o = {"-p" => '1999',
        "-i" => keypair.full_filepath,
        "-o" =>"StrictHostKeyChecking=no"
      }.merge(opts)
      o.collect{ |k,v| "#{k} #{v}"}.join(' ')
    end
    def scp_options(opts={})
      o = {"-P" => '1999',
        "-i" => keypair.full_filepath,
        "-o" =>"StrictHostKeyChecking=no"
      }.merge(opts)
      o.collect{ |k,v| "#{k} #{v}"}.join(' ')
    end
  end
end

However, these module attributes are not used uniformly throughout PoolParty.

**Comment by auser** [comment]
In your using block, try setting this as options:

```
using :ec2, :"-P" => "1999" do
end
```

**Comment by tralfamadude** [comment]
Workaround:  if your provisioner machine allows, setting your ssh defaults (usually ssh_config under /etc or /etc/ssh/) to have "Port 1999" will cause the right thing to happen.  

A related, interesting fact:  sshd can listen on more than one port, so standard port 22 can be opened temporarily.
