### ISSUE TITLE
Error running cloud-start

### ISSUE THREAD

**Issue by mklatsky** [auser/poolparty#53]
Running poolparty 1.3.16:

cloud-list provides listing- correctly.

Attempting to to run 'cloud-start' throws:
warning: peer certificate won't be verified in this SSL session
/var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:30:in `expand_path': can't convert nil into String (TypeError)
from /var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:30:in`full_filepath'  
        from /var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:19:in `exists?'                                  
        from /var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:90:in`keypair_found?'
        from /var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:73:in `send'
        from /var/lib/gems/1.8/gems/auser-poolparty-1.3.16/bin/../lib/keypair.rb:73:in`valid?

...and more which I can provide.

Thanks-

MK

**Comment by auser** [comment]
That's a known issue... We are resolving it now :\

**Comment by portertech** [comment]
Still an issue for me. V 1.3.17 ../lib/keypair.rb:32:in `expand_path': can't convert nil into String (TypeError)

**Comment by auser** [comment]
The gem version should be 1.4. Grab it off gemcutter.org
    gem sources -a http://gemcutter.org
    gem install poolparty
