### ISSUE TITLE
security_group fails when name is provided

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#55]
Running something like the following fails with an error stating that the security group doesn't exist (obviously... it's supposed to be created by poolparty):
    security_group 'my_security_group' do ...

Removing the name from the security_group call leads to a default name (<pool name>-<cloud name>) and the security group is created.

**Comment by contentfree** [comment]
Still an issue?

**Comment by auser** [comment]
This should be fixed with the latest push

**Comment by auser** [comment]
Closing this issue.
