### ISSUE TITLE
/lib/poolparty/cloud.rb:141: syntax error, unexpected ',', expecting '|' (SyntaxError)

### ISSUE THREAD

**Issue by scottburton11** [auser/poolparty#60]
Backtrace here: http://gist.github.com/228501

**Comment by auser** [comment]
What version of ruby are you running?

**Comment by scottburton11** [comment]
Stock Leopard ruby:

ruby -v
ruby 1.8.6 (2008-08-11 patchlevel 287) [universal-darwin9.0]

**Comment by auser** [comment]
I just pushed a change to the source that should support ruby 1.8.6. Can you test it to make sure?

I've tested locally to confirm here.

**Comment by scottburton11** [comment]
Works!

Thanks for the patch.

**Comment by auser** [comment]
No prob! Glad we could fix it
