### ISSUE TITLE
Haproxy doesn't work because there's no hosts for VirtualHost *:8080

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#7]
The default site (vendor/chef/apache2/templates/default/default-site.erb) is for VirtualHost *:80. 

ports.conf correctly tells Apache to Listen on 8080 and create a NameVirtualHost for 8080, but because of the above default site there's nothing that responds at 8080 and haproxy reports everything down.

**Comment by contentfree** [comment]
This should be fixed in my commit 8392fce91da8d759097377a120a3ddf0f78775f6 to contentfree/vmrun

**Comment by auser** [comment]
Fixed in latest 1.2.3. Must include haproxy block after apache block. Also, you can now use the calls => helper for plugins. I.e.:

<pre><code>
      haproxy do
        calls get_exec("reload-apache2") 
      end
</code></pre>
