### ISSUE TITLE
Haproxy can't forward to the IP addresses given in the config file

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#8]
/usr/bin/server-list-active reports the external IP addresses, not the internal IP addresses. Once you get the other issues corrected (see the other tickets), haproxy _still_ doesn't work because it can't forward to the given IPs.

Setting them to 127.0.0.1 - or presumably the internal IP addresses reported via ifconfig - corrects the problem.

**Comment by contentfree** [comment]
This should be fixed in my commit 8392fce91da8d759097377a120a3ddf0f78775f6 to contentfree/vmrun

**Comment by auser** [comment]
Merged branch and should be fixed on master
