### ISSUE TITLE
vmrun branch doesn't copy up server-* bins so the haproxy configuration fails

### ISSUE THREAD

**Issue by contentfree** [auser/poolparty#9]
I did a `rm -fr /tmp/poolparty` and tried to `cloud start`. At no point is the binary /usr/bin/server-list-active copied up to the server, so the configuration of haproxy fails because the haproxy.conf template uses server-list-active to get the IP addresses.

It worked _before_ I cleared /tmp/poolparty when I had remnants from a previous provisioning (while on the master branch)

**Comment by auser** [comment]
This should be fixed with the newest branch merge
