### ISSUE TITLE
Puppet support

### ISSUE THREAD

**Issue by jamtur01** [auser/poolparty#95]
It'd be great if poolparty integrated Puppet as well.  It's on my list to look at but it's a long list.  Just thought I'd add the ticket as a reference.

**Comment by fairchild** [comment]
The current thinking is that support for provisioners will be extracted out of poolparty and poolparty will focus on defining the infrastructure.  Chef support wil be able to be added thru a plugin or extension, or by just having some userdata that installs chef,/puppet grabs the cookbooks and exectues them.

**Comment by jamtur01** [comment]
Sounds good.  What's the timeline for that?
